server:
  port: 8030

debug: true

# 注释
spring:
  application:
    name: gateway
  cloud:
#    consul:
#      host: localhost
#      port: 8500
    gateway:
      x-forwarded:
        forEnabled: false
      routes:
      - id: a_route
        uri: lb://biz-bar
        predicates:
        - Path=/test/**
      - id: b_route
        uri: lb://biz-foo
        predicates:
        - Path=/**
      - id: b_route2
        uri: lb://biz-bar
        predicates:
        - Path=/get
#http://example.org