server:
  port: 8030

#debug: true

# 注释
spring:
  application:
    name: gateway
  cloud:
#    consul:
#      host: localhost
#      port: 8500
    gateway:
      routes:
      - id: a_route
        uri: lb://biz-bar
        predicates:
        - Path=/test/**
      - id: b_route
        uri: lb://biz-foo
        predicates:
        - Path=/*
#http://example.org