server:
  port: 8030

#debug: true

# 注释
spring:
  application:
    name: gateway
  
  cloud:
    consul:
      host: localhost
      port: 8500
    gateway:
      routes:
#      - id: a_route
#        uri: http://example.org
#        predicates:
#        - Query=baz=.*m.*
      - id: b_route
        uri: lb://biz-foo1
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#http://example.org