
server:
  port: 8100

spring:
  profiles:
    active: dev
  application:
    name: consul-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: consul-provider
        #healthCheckPath: 
        