
server:
  port: 8100

spring:
  profiles:
    active: dev
  application:
    name: biz-bar
  cloud:
    consul:
      host: localhost
      port: 8500
#      discovery:
#        serviceName: biz-bar
