server:
  port: 8110

#debug: true

spring:
  profiles:
    active: dev
  application:
    name: biz-foo
# 资源路由关且开启异常    
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  cloud:
    consul:
      host: localhost
      port: 8500
#      discovery:
#        serviceName: zzz
# discovery.serviceName可以不配

#feign.httpclient.enabled=false
#feign.okhttp.enabled=true

feign:
#  okhttp:
#    enabled: true
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#        retryer: feign.Retryer.Default



## 这个要有，如果不加，只加了上面也没用？？已废弃
#ribbon:
#  restclient:
#    enabled: false

